title: Jiale Yuan's Homepage
page-top-title: Jiale Yuan
top-section-bg-text: Computer Science
home-subtitle: Jiale Yuan&ensp;|&ensp;袁家乐
copyright-text: '&copy; Jiale Yuan 2024-2025. All Rights Reserved.'